import { Patient } from "./types";

export const MOCK_NEW_APPOINTMENTS: Patient[] = [
  {
    id: "new-1",
    name: "Yelena Isinbaeva",
    age: 32,
    email: "yelena@example.com",
    diagnosis: "Fever",
    description: "I’ve had a fever for three days with chills, body aches, and fatigue.",
    status: "Waiting",
    dateTime: "Waiting",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/f3dc26797671e7caea0bc2f0647901599c916831?width=72",
    bio: "Yelena Isinbaeva is a 32-year-old female diagnosed with a high fever. She has a history of seasonal allergies and is proactive about seeking treatment when symptoms persist. She is looking for an immediate consultation to address the fever, chills, and body aches.",
    preVisitFormDate: "17 Oct, 2020, 11:40 PM",
    preVisitForm: {
      chronicIllnesses: "Seasonal allergies",
      currentMedications: "-Cetirizine 10mg – Take one tablet daily.\n-Paracetamol 500mg – As needed for fever.",
      allergies: "Dust, pollen",
      primaryConcern: "High fever for three days with chills and body aches.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "new-2",
    name: "Albert Flores",
    age: 89,
    email: "albert.flores@example.com",
    diagnosis: "Cough",
    description: "I’ve had a persistent dry cough for the past week with throat irritation.",
    status: "Scheduled",
    dateTime: "17 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/193603633a5140267134f1748cf7c4365ae534a9?width=72",
    bio: "John Smith is a 45-year-old male from Sharjah, UAE, diagnosed with hypertension. He has a history of Type 2 Diabetes and is currently on medication for both conditions. John follows a regular exercise routine and maintains a controlled diet to manage his health. He regularly attends check-ups and is proactive about his well-being.",
    preVisitFormDate: "17 Oct, 2020, 11:40 PM",
    preVisitForm: {
      chronicIllnesses: "No",
      currentMedications: "-Amlodipine 10mg - Take one tablet daily.\n-Metformin 500mg - Continue as prescribed.\n-Ibuprofen 400mg - As needed for headache relief.",
      allergies: "None",
      primaryConcern: "Persistent headaches and fatigue.",
      smokes: "No",
      drinks: "Yes"
    }
  },
  {
    id: "new-3",
    name: "Savannah Nguyen",
    age: 32,
    email: "savannah.n@example.com",
    diagnosis: "Asthma",
    description: "Mild asthma flare-up triggered by change in weather, needing inhaler adjustment.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/2fc70c27396226e96d788f42ab8214ce8f948ab5?width=72",
    bio: "Savannah Nguyen is a 32-year-old female who has been managing mild asthma since childhood. She uses a rescue inhaler when needed and is visiting for a routine check-up and prescription renewal. She is otherwise in good health and maintains an active lifestyle.",
    preVisitFormDate: "20 Oct, 2020, 09:15 AM",
    preVisitForm: {
      chronicIllnesses: "Asthma (since childhood)",
      currentMedications: "-Albuterol inhaler – As needed.\n-Fluticasone 100mcg – Daily preventive.",
      allergies: "Pollen, dust mites",
      primaryConcern: "Worsening shortness of breath due to weather change.",
      smokes: "No",
      drinks: "Occasionally"
    }
  },
  {
    id: "new-4",
    name: "Darlene Robertson",
    age: 32,
    email: "darlene.r@example.com",
    diagnosis: "Cough",
    description: "Acute chest congestion with painful cough and occasional shortness of breath.",
    status: "Scheduled",
    dateTime: "21 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/05a901293de2a84f45dff39e0efa33b0984e765e?width=72",
    bio: "Darlene Robertson is a 32-year-old female presenting with a persistent dry cough for the past week. She has no significant medical history but reports mild throat irritation and congestion. She is seeking advice on symptomatic relief.",
    preVisitFormDate: "19 Sep, 2020, 02:30 PM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "None currently",
      allergies: "Penicillin",
      primaryConcern: "Dry cough with chest tightness for one week.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "new-5",
    name: "Cody Fisher",
    age: 32,
    email: "cody.f@example.com",
    diagnosis: "Fever",
    description: "Sudden onset of fever over 101F with body pain and headache.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b4cc7594fc29dd53530bda4ab8cd965eebd0526d?width=72",
    bio: "Cody Fisher is a 32-year-old male who has been experiencing a fever, fatigue, and muscle aches for three days. He has no chronic conditions and is looking for a professional assessment and potential treatment options.",
    preVisitFormDate: "21 Oct, 2020, 04:45 PM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "Paracetamol 500mg – As needed for fever.",
      allergies: "None known",
      primaryConcern: "High fever with body aches and severe headache.",
      smokes: "No",
      drinks: "Occasionally"
    }
  }
];

export const MOCK_ALL_CONSULTATIONS: Patient[] = [
  {
    id: "all-1",
    name: "Brooklyn Simmons",
    age: 32,
    email: "brooklyn.s@example.com",
    diagnosis: "Fever",
    description: "Recovering from viral fever, seeking follow-up on temperature stability.",
    status: "Waiting",
    dateTime: "Waiting",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/75256e943440be4cb0a85199610fc72cb903d28c?width=72",
    bio: "Brooklyn Simmons is a 32-year-old female who recently recovered from a moderate fever. Her follow-up visit is to ensure that her vital signs are stable and no secondary infection has developed.",
    preVisitFormDate: "20 Sep, 2020, 06:10 PM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "Paracetamol 500mg – As needed.",
      allergies: "None",
      primaryConcern: "Recovering from viral fever",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "all-2",
    name: "Albert Flores",
    age: 89,
    email: "albert.flores@example.com",
    diagnosis: "Cough",
    description: "I’ve had a persistent dry cough for the past week with throat irritation.",
    status: "Scheduled",
    dateTime: "8 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/2fc70c27396226e96d788f42ab8214ce8f948ab5?width=72",
    bio: "John Smith is a 45-year-old male from Sharjah, UAE, diagnosed with hypertension. He has a history of Type 2 Diabetes and is currently on medication for both conditions. John follows a regular exercise routine and maintains a controlled diet to manage his health. He regularly attends check-ups and is proactive about his well-being.",
    preVisitFormDate: "8 Sep, 2020, 11:40 PM",
    preVisitForm: {
      chronicIllnesses: "No",
      currentMedications: "-Amlodipine 10mg - Take one tablet daily.\n-Metformin 500mg - Continue as prescribed.",
      allergies: "None",
      primaryConcern: "Persistent headaches and fatigue.",
      smokes: "No",
      drinks: "Yes"
    }
  },
  {
    id: "all-3",
    name: "Cameron Williamson",
    age: 32,
    email: "cameron.w@example.com",
    diagnosis: "Asthma",
    description: "Routine assessment of exercise-induced asthma control.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b68921b9bb9ab8729018822005356cd9a7bdb3d5?width=72",
    bio: "Cameron Williamson is a 32-year-old male with moderate asthma. His session in October was a routine asthma control assessment, and his inhaler dose was adjusted accordingly.",
    preVisitFormDate: "21 Oct, 2020, 03:00 PM",
    preVisitForm: {
      chronicIllnesses: "Moderate asthma",
      currentMedications: "-Albuterol inhaler – As needed.",
      allergies: "Dust, pollen",
      primaryConcern: "Routine assessment of exercise-induced asthma control.",
      smokes: "No",
      drinks: "Occasionally"
    }
  },
  {
    id: "all-4",
    name: "Courtney Henry",
    age: 32,
    email: "courtney.h@example.com",
    diagnosis: "Cough",
    description: "Mild bronchitis symptoms following cold, seeking guidance.",
    status: "Scheduled",
    dateTime: "8 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/05a901293de2a84f45dff39e0efa33b0984e765e?width=72",
    bio: "Courtney Henry is a 32-year-old female who presented with an acute cough following a viral upper respiratory infection. Her symptoms cleared up after a course of supportive therapy.",
    preVisitFormDate: "7 Sep, 2020, 01:40 PM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "None currently",
      allergies: "None",
      primaryConcern: "Mild bronchitis symptoms following cold.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "all-5",
    name: "Bessie Cooper",
    age: 32,
    email: "bessie.cooper@example.com",
    diagnosis: "Fever",
    description: "Fever for three days with chills and fatigue.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/a6e1aefad7124efd79b13f8c10e84778817f96f0?width=72",
    bio: "Bessie Cooper is a 32-year-old female who presented with fever and body aches. A routine evaluation was done to rule out influenza.",
    preVisitFormDate: "22 Oct, 2020, 10:10 AM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "Paracetamol as needed",
      allergies: "None",
      primaryConcern: "Fever for three days with chills and fatigue.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "all-6",
    name: "Bessie Cooper",
    age: 28,
    email: "bessie.c2@example.com",
    diagnosis: "Fever",
    description: "Recurring mild fever in evenings.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/70edbe32982956e0679a8ff727695d9b1777fc72?width=72",
    bio: "Bessie Cooper, 28, presented with low-grade evening fevers. Blood panels were ordered to check for inflammatory markers.",
    preVisitFormDate: "22 Oct, 2020, 08:30 AM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "Paracetamol as needed",
      allergies: "None",
      primaryConcern: "Recurring mild fever in evenings.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "all-7",
    name: "Bessie Cooper",
    age: 35,
    email: "bessie.c3@example.com",
    diagnosis: "Fever",
    description: "High fever accompanied by severe sore throat.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/849e04b65fc61409106af3d69a42e91596c64bd2?width=72",
    bio: "Bessie Cooper, 35, complained of a sudden fever and throat discomfort. Swift strep test was conducted during the call.",
    preVisitFormDate: "21 Oct, 2020, 11:00 PM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "None",
      allergies: "None",
      primaryConcern: "High fever accompanied by severe sore throat.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "all-8",
    name: "Bessie Cooper",
    age: 41,
    email: "bessie.c4@example.com",
    diagnosis: "Fever",
    description: "Post-vaccination high fever and chills.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/9095e778a7eba1729febd7b2a1d7026c11d62d63?width=72",
    bio: "Bessie Cooper, 41, experienced immune response fevers following booster immunizations. Recommended paracetamol regimen.",
    preVisitFormDate: "22 Oct, 2020, 09:00 AM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "None",
      allergies: "None",
      primaryConcern: "Post-vaccination high fever and chills.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "all-9",
    name: "Bessie Cooper",
    age: 50,
    email: "bessie.c5@example.com",
    diagnosis: "Fever",
    description: "Fever, body aches, joint stiffness.",
    status: "Scheduled",
    dateTime: "22 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/5c080405a4cfd0cc48c023c7e3ca5054f6c0c807?width=72",
    bio: "Bessie Cooper, 50, sought consultation for a fever combined with joint pain. Referred to rheumatology for a follow-up check.",
    preVisitFormDate: "20 Oct, 2020, 05:45 PM",
    preVisitForm: {
      chronicIllnesses: "None",
      currentMedications: "None",
      allergies: "None",
      primaryConcern: "Fever, body aches, joint stiffness.",
      smokes: "No",
      drinks: "No"
    }
  },
  {
    id: "all-10",
    name: "Esther Howard",
    age: 45,
    email: "esther.howard@example.com",
    diagnosis: "Migraine",
    description: "Severe throbbing pain behind left eye with nausea and light sensitivity.",
    status: "Completed",
    dateTime: "15 Oct, 2020, 10:15 AM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/193603633a5140267134f1748cf7c4365ae534a9?width=72",
    bio: "Esther Howard is a 45-year-old female presenting with chronic migraine episodes. She is on triptans and seeking lifestyle counseling to avoid common triggers.",
    preVisitFormDate: "14 Oct, 2020, 08:30 PM"
  },
  {
    id: "all-11",
    name: "Leslie Alexander",
    age: 38,
    email: "leslie.alexander@example.com",
    diagnosis: "Allergy",
    description: "Severe hives and swelling on hands, suspected food allergen.",
    status: "Completed",
    dateTime: "12 Oct, 2020, 02:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/f3dc26797671e7caea0bc2f0647901599c916831?width=72",
    bio: "Leslie Alexander is a 38-year-old male experiencing acute hives. Antihistamine was prescribed and referred for comprehensive allergy prick tests.",
    preVisitFormDate: "12 Oct, 2020, 11:20 AM"
  },
  {
    id: "all-12",
    name: "Jane Cooper",
    age: 29,
    email: "jane.cooper@example.com",
    diagnosis: "Asthma",
    description: "Dry persistent cough and chest tightness during morning runs.",
    status: "Completed",
    dateTime: "10 Oct, 2020, 09:00 AM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/2fc70c27396226e96d788f42ab8214ce8f948ab5?width=72",
    bio: "Jane Cooper is a 29-year-old female runner experiencing exercise-induced bronchoconstriction. Albuterol inhaler prescribed for use pre-exercise.",
    preVisitFormDate: "09 Oct, 2020, 04:00 PM"
  },
  {
    id: "all-13",
    name: "Robert Fox",
    age: 44,
    email: "robert.fox@example.com",
    diagnosis: "Fever",
    description: "Fever and cold symptoms for 2 days.",
    status: "Completed",
    dateTime: "09 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b4cc7594fc29dd53530bda4ab8cd965eebd0526d?width=72",
    bio: "Robert Fox is a 44-year-old male presenting with mild viral fever.",
    preVisitFormDate: "09 Oct, 2020, 10:00 AM"
  },
  {
    id: "all-14",
    name: "Guy Hawkins",
    age: 36,
    email: "guy.hawkins@example.com",
    diagnosis: "Cough",
    description: "Dry cough with slight wheezing.",
    status: "Completed",
    dateTime: "08 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/75256e943440be4cb0a85199610fc72cb903d28c?width=72",
    bio: "Guy Hawkins is a 36-year-old male presenting with mild bronchial cough.",
    preVisitFormDate: "08 Oct, 2020, 09:30 AM"
  },
  {
    id: "all-15",
    name: "Kristin Watson",
    age: 32,
    email: "kristin.w@example.com",
    diagnosis: "Asthma",
    description: "Shortness of breath on mild exertion.",
    status: "Completed",
    dateTime: "07 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/2fc70c27396226e96d788f42ab8214ce8f948ab5?width=72",
    bio: "Kristin Watson is a 32-year-old female tracking her asthma treatment plan.",
    preVisitFormDate: "07 Oct, 2020, 04:00 PM"
  },
  {
    id: "all-16",
    name: "Eleanor Pena",
    age: 51,
    email: "eleanor.p@example.com",
    diagnosis: "Fever",
    description: "Chills and fever after travel abroad.",
    status: "Completed",
    dateTime: "06 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b68921b9bb9ab8729018822005356cd9a7bdb3d5?width=72",
    bio: "Eleanor Pena is a 51-year-old female presenting with a travel-related fever.",
    preVisitFormDate: "05 Oct, 2020, 11:00 AM"
  },
  {
    id: "all-17",
    name: "Devon Lane",
    age: 27,
    email: "devon.lane@example.com",
    diagnosis: "Cough",
    description: "Post-viral cough, throat feels dry.",
    status: "Completed",
    dateTime: "05 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/05a901293de2a84f45dff39e0efa33b0984e765e?width=72",
    bio: "Devon Lane is a 27-year-old male seeking consultation for coughing spasms.",
    preVisitFormDate: "04 Oct, 2020, 02:00 PM"
  },
  {
    id: "all-18",
    name: "Marvin McKinney",
    age: 42,
    email: "marvin.mck@example.com",
    diagnosis: "Asthma",
    description: "Seasonal asthma symptoms aggravated by pollen.",
    status: "Completed",
    dateTime: "04 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b4cc7594fc29dd53530bda4ab8cd965eebd0526d?width=72",
    bio: "Marvin McKinney is a 42-year-old male with persistent pollen allergies and mild asthma.",
    preVisitFormDate: "03 Oct, 2020, 08:30 AM"
  },
  {
    id: "all-19",
    name: "Jerome Bell",
    age: 33,
    email: "jerome.bell@example.com",
    diagnosis: "Fever",
    description: "High fever of 102F since yesterday.",
    status: "Completed",
    dateTime: "03 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/193603633a5140267134f1748cf7c4365ae534a9?width=72",
    bio: "Jerome Bell is a 33-year-old male presenting with acute high-grade fever.",
    preVisitFormDate: "03 Oct, 2020, 10:45 AM"
  },
  {
    id: "all-20",
    name: "Floyd Miles",
    age: 48,
    email: "floyd.miles@example.com",
    diagnosis: "Cough",
    description: "Deep productive cough for 5 days.",
    status: "Completed",
    dateTime: "02 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/f3dc26797671e7caea0bc2f0647901599c916831?width=72",
    bio: "Floyd Miles is a 48-year-old male presenting with chest congestion and cough.",
    preVisitFormDate: "02 Oct, 2020, 08:00 AM"
  },
  {
    id: "all-21",
    name: "Albert Flores",
    age: 89,
    email: "albert.flores@example.com",
    diagnosis: "Cough",
    description: "Severe cough, feeling fatigued.",
    status: "Completed",
    dateTime: "01 Oct, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/193603633a5140267134f1748cf7c4365ae534a9?width=72",
    bio: "Albert Flores is an 89-year-old male checking on post-infection recovery progress.",
    preVisitFormDate: "01 Oct, 2020, 09:15 AM"
  },
  {
    id: "all-22",
    name: "Wade Warren",
    age: 31,
    email: "wade.warren@example.com",
    diagnosis: "Fever",
    description: "Low-grade fever and mild headache.",
    status: "Completed",
    dateTime: "30 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/2fc70c27396226e96d788f42ab8214ce8f948ab5?width=72",
    bio: "Wade Warren is a 31-year-old male experiencing fatigue and mild fever.",
    preVisitFormDate: "30 Sep, 2020, 02:40 PM"
  },
  {
    id: "all-23",
    name: "Theresa Webb",
    age: 45,
    email: "theresa.webb@example.com",
    diagnosis: "Asthma",
    description: "Needs inhaler prescription refill, chest is clear.",
    status: "Completed",
    dateTime: "29 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b68921b9bb9ab8729018822005356cd9a7bdb3d5?width=72",
    bio: "Theresa Webb is a 45-year-old female managing mild seasonal asthma.",
    preVisitFormDate: "28 Sep, 2020, 03:00 PM"
  },
  {
    id: "all-24",
    name: "Dianne Russell",
    age: 29,
    email: "dianne.r@example.com",
    diagnosis: "Cough",
    description: "Coughing fit triggered by cold fluids.",
    status: "Completed",
    dateTime: "28 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/05a901293de2a84f45dff39e0efa33b0984e765e?width=72",
    bio: "Dianne Russell is a 29-year-old female presenting with throat hypersensitivity.",
    preVisitFormDate: "28 Sep, 2020, 09:30 AM"
  },
  {
    id: "all-25",
    name: "Ronald Richards",
    age: 50,
    email: "ronald.r@example.com",
    diagnosis: "Fever",
    description: "Fever spikes in early morning, feeling body aches.",
    status: "Completed",
    dateTime: "27 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b4cc7594fc29dd53530bda4ab8cd965eebd0526d?width=72",
    bio: "Ronald Richards is a 50-year-old male monitoring viral symptoms.",
    preVisitFormDate: "27 Sep, 2020, 08:30 AM"
  },
  {
    id: "all-26",
    name: "Darrell Steward",
    age: 38,
    email: "darrell.s@example.com",
    diagnosis: "Cough",
    description: "Cough with mild respiratory discomfort.",
    status: "Completed",
    dateTime: "26 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/a6e1aefad7124efd79b13f8c10e84778817f96f0?width=72",
    bio: "Darrell Steward is a 38-year-old male checking on cough status.",
    preVisitFormDate: "26 Sep, 2020, 11:00 AM"
  },
  {
    id: "all-27",
    name: "Kathryn Murphy",
    age: 32,
    email: "kathryn.m@example.com",
    diagnosis: "Asthma",
    description: "Asthma checkup, feeling better than last week.",
    status: "Completed",
    dateTime: "25 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/70edbe32982956e0679a8ff727695d9b1777fc72?width=72",
    bio: "Kathryn Murphy is a 32-year-old female verifying her asthma dosage.",
    preVisitFormDate: "24 Sep, 2020, 02:30 PM"
  },
  {
    id: "all-28",
    name: "Eleanor Watson",
    age: 26,
    email: "eleanor.w@example.com",
    diagnosis: "Fever",
    description: "Mild fever and sore throat.",
    status: "Completed",
    dateTime: "24 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/849e04b65fc61409106af3d69a42e91596c64bd2?width=72",
    bio: "Eleanor Watson is a 26-year-old female presenting with cold symptoms.",
    preVisitFormDate: "24 Sep, 2020, 09:00 AM"
  },
  {
    id: "all-29",
    name: "Bessie Cooper",
    age: 33,
    email: "bessie.c@example.com",
    diagnosis: "Fever",
    description: "Fever of 100.5F with body ache.",
    status: "Completed",
    dateTime: "23 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/9095e778a7eba1729febd7b2a1d7026c11d62d63?width=72",
    bio: "Bessie Cooper is a 33-year-old female recovering from mild flu symptoms.",
    preVisitFormDate: "22 Sep, 2020, 06:10 PM"
  },
  {
    id: "all-30",
    name: "Arlene Simmons",
    age: 29,
    email: "arlene.s@example.com",
    diagnosis: "Cough",
    description: "Tickling cough, throat irritation.",
    status: "Completed",
    dateTime: "22 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/5c080405a4cfd0cc48c023c7e3ca5054f6c0c807?width=72",
    bio: "Arlene Simmons is a 29-year-old female checking for cough relief option.",
    preVisitFormDate: "22 Sep, 2020, 08:30 AM"
  },
  {
    id: "all-31",
    name: "Esther Henry",
    age: 41,
    email: "esther.h@example.com",
    diagnosis: "Asthma",
    description: "Routine check on bronchial asthma.",
    status: "Completed",
    dateTime: "21 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/193603633a5140267134f1748cf7c4365ae534a9?width=72",
    bio: "Esther Henry is a 41-year-old female managing bronchial asthma control.",
    preVisitFormDate: "21 Sep, 2020, 10:20 AM"
  },
  {
    id: "all-32",
    name: "Kristin Miles",
    age: 35,
    email: "kristin.m@example.com",
    diagnosis: "Fever",
    description: "Fever and chills starting last night.",
    status: "Completed",
    dateTime: "20 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/f3dc26797671e7caea0bc2f0647901599c916831?width=72",
    bio: "Kristin Miles is a 35-year-old female checking on viral symptoms progress.",
    preVisitFormDate: "20 Sep, 2020, 09:15 AM"
  },
  {
    id: "all-33",
    name: "Jenny Wilson",
    age: 28,
    email: "jenny.w@example.com",
    diagnosis: "Cough",
    description: "Cold and cough symptoms.",
    status: "Completed",
    dateTime: "19 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/2fc70c27396226e96d788f42ab8214ce8f948ab5?width=72",
    bio: "Jenny Wilson is a 28-year-old female checking throat irritation remedies.",
    preVisitFormDate: "19 Sep, 2020, 11:20 AM"
  },
  {
    id: "all-34",
    name: "Alice Johnson",
    age: 34,
    email: "alice.j@example.com",
    diagnosis: "Asthma",
    description: "Check on inhaler response.",
    status: "Completed",
    dateTime: "18 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/b68921b9bb9ab8729018822005356cd9a7bdb3d5?width=72",
    bio: "Alice Johnson is a 34-year-old female verifying her asthma plan.",
    preVisitFormDate: "18 Sep, 2020, 04:00 PM"
  },
  {
    id: "all-35",
    name: "Bob Anderson",
    age: 45,
    email: "bob.a@example.com",
    diagnosis: "Fever",
    description: "Fever and headaches.",
    status: "Completed",
    dateTime: "17 Sep, 2020, 11:40 PM",
    avatar: "https://api.builder.io/api/v1/image/assets/TEMP/05a901293de2a84f45dff39e0efa33b0984e765e?width=72",
    bio: "Bob Anderson is a 45-year-old male with persistent viral headaches.",
    preVisitFormDate: "16 Sep, 2020, 11:40 PM"
  }
];
